### ISSUE TITLE
apm not respecting git config --global url."https://".insteadOf git://

### ISSUE THREAD

**Issue by ceeeKay** [atom/apm#106]
Attempting to build Atom on a system behind a firewall that doesn't allow the git:// protocol out.

My ~/.gitconfig contains
```
[url "https://"]
	insteadOf = git://
```

As far as I can tell this seems to be an apm issue, but I'm not sure if it could be in atom or npm code (the lines are unclear to me).

```
  SOLINK_MODULE(target) Release/obj.target/git.node
  SOLINK_MODULE(target) Release/obj.target/git.node: Finished
  COPY Release/git.node
make: Leaving directory `/build/ceeeKay/atom/node_modules/git-utils/build'

npm WARN engine specificity@0.1.3: wanted: {"node":"~0.8.x"} (current: {"node":"v0.10.26","npm":"1.4.4"})
npm WARN engine specificity@0.1.3: wanted: {"node":"~0.8.x"} (current: {"node":"v0.10.26","npm":"1.4.4"})
npm ERR! git clone git://github.com/atom/slick.git Cloning into bare repository '/users/ceeeKay/.atom/.node-gyp/.atom/.apm/_git-remotes/git-github-com-atom-slick-git-fe3034e1'...
npm ERR! git clone git://github.com/atom/slick.git 
npm ERR! git clone git://github.com/atom/slick.git fatal: unable to connect to github.com:
npm ERR! git clone git://github.com/atom/slick.git github.com[0: 192.30.252.129]: errno=Connection timed out
npm ERR! Error: Command failed: fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.129]: errno=Connection timed out
npm ERR! 
npm ERR! 
npm ERR!     at ChildProcess.exithandler (child_process.js:637:15)
npm ERR!     at ChildProcess.EventEmitter.emit (events.js:98:17)
npm ERR!     at maybeClose (child_process.js:743:16)
npm ERR!     at Socket.<anonymous> (child_process.js:956:11)
npm ERR!     at Socket.EventEmitter.emit (events.js:95:17)
npm ERR!     at Pipe.close (net.js:465:12)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 2.6.32-431.11.2.el6.centos.plus.x86_64
npm ERR! command "/build/ceeeKay/atom/apm/node_modules/atom-package-manager/bin/node" "/build/ceeeKay/atom/apm/node_modules/atom-package-manager/node_modules/npm/bin/npm-cli.js" "--userconfig" "/build/ceeeKay/atom/apm/node_modules/atom-package-manager/.apmrc" "install" "--target=0.11.10" "--arch=x64" "--quiet"
npm ERR! cwd /build/ceeeKay/atom
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.4
npm ERR! code 128
npm ERR! git clone git://github.com/benogle/jsdiff.git Cloning into bare repository '/users/ceeeKay/.atom/.node-gyp/.atom/.apm/_git-remotes/git-github-com-benogle-jsdiff-git-b9e372e4'...
npm ERR! git clone git://github.com/benogle/jsdiff.git 
npm ERR! git clone git://github.com/benogle/jsdiff.git fatal: unable to connect to github.com:
npm ERR! git clone git://github.com/benogle/jsdiff.git github.com[0: 192.30.252.129]: errno=Connection timed out
npm ERR! git clone git://github.com/kevinsawicki/jasmine-node.git Cloning into bare repository '/users/ceeeKay/.atom/.node-gyp/.atom/.apm/_git-remotes/git-github-com-kevinsawicki-jasmine-node-git-7c50cc1a'...
npm ERR! git clone git://github.com/kevinsawicki/jasmine-node.git 
npm ERR! git clone git://github.com/kevinsawicki/jasmine-node.git fatal: unable to connect to github.com:
npm ERR! git clone git://github.com/kevinsawicki/jasmine-node.git github.com[0: 192.30.252.129]: errno=Connection timed out
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /build/ceeeKay/atom/npm-debug.log
npm ERR! not ok code 0
```

**Comment by 50Wliu** [comment]
Closed upstream, so I'm going to close this as well.
