### ISSUE TITLE
npm install atom-package-manager fails on Windows

### ISSUE THREAD

**Issue by combiths** [atom/apm#205]
Greetings,

I just tried installing atom-package-manager from my Git Bash window and received the following errors. Git version is 1.9.4.msysgit.2. Already tried: "npm config set python <path to Python 2.7>"
Thanks.

```
$ npm install atom-package-manager -g
\
> keytar@2.0.3 install C:\Users\Daniel\AppData\Roaming\npm\node_modules\atom-package-manager\node_modules\keytar
> node-gyp rebuild

C:\Users\Daniel\AppData\Roaming\npm\node_modules\atom-package-manager\node_modules\keytar>node "c:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
gyp ERR! configure error
gyp ERR! stack Error: spawn ENOENT
gyp ERR! stack     at errnoException (child_process.js:1001:11)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:792:34)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "c:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Daniel\AppData\Roaming\npm\node_modules\atom-package-manager\node_modules\keytar
gyp ERR! node -v v0.10.32
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok
-
> oniguruma@3.0.4 install C:\Users\Daniel\AppData\Roaming\npm\node_modules\atom-package-manager\node_modules\first-mate\node_modules\oniguruma
> node-gyp rebuild

C:\Users\Daniel\AppData\Roaming\npm\node_modules\atom-package-manager\node_modules\first-mate\node_modules\oniguruma>node "c:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin
gyp ERR! configure error
gyp ERR! stack Error: spawn ENOENT
gyp ERR! stack     at errnoException (child_process.js:1001:11)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:792:34)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "c:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Daniel\AppData\Roaming\npm\node_modules\atom-package-manager\node_modules\first-mate\node_modules\oniguruma
gyp ERR! node -v v0.10.32
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok
npm WARN package.json github-url-from-git@1.1.1 No repository field.
/
> git-utils@2.1.5 install C:\Users\Daniel\AppData\Roaming\npm\node_modules\atom-package-manager\node_modules\git-utils
> node-gyp rebuild

C:\Users\Daniel\AppData\Roaming\npm\node_modules\atom-package-manager\node_modules\git-utils>node "c:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
gyp ERR! configure error
gyp ERR! stack Error: spawn ENOENT
gyp ERR! stack     at errnoException (child_process.js:1001:11)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:792:34)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "c:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Daniel\AppData\Roaming\npm\node_modules\atom-package-manager\node_modules\git-utils
gyp ERR! node -v v0.10.32
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

npm ERR! keytar@2.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the keytar@2.0.3 install script.
npm ERR! This is most likely a problem with the keytar package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls keytar
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.2.9200
npm ERR! command "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "atom-package-manager" "-g"
npm ERR! cwd C:\Users\Daniel
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

Also tried with Powershell as administrator and got the following (same output when using package manager in Atom GUI):

```
PS C:\windows\system32> npm install atom-package-manager -g
npm ERR! git fetch -a origin (https://github.com/nathansobo/node-plist.git) fatal: Unable to find remote helper for 'https'
npm ERR! Error: Command failed: fatal: Unable to find remote helper for 'https'
npm ERR!
npm ERR!     at ChildProcess.exithandler (child_process.js:648:15)
npm ERR!     at ChildProcess.emit (events.js:98:17)
npm ERR!     at maybeClose (child_process.js:756:16)
npm ERR!     at Process.ChildProcess._handle.onexit (child_process.js:823:5)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "atom-package-manager" "-g"
npm ERR! cwd C:\windows\system32
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code 128
npm ERR! not ok code 0
```

**Comment by orlin** [comment]
This fails on Mac OSX (Yosemite) too, it appears also due to keytar.  Using Command Line Tools 7.1 and node 4.2.1 or 4.2.2.  Here's what npm says:

```
SOLINK_MODULE(target) Release/git.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/git.node] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/om/.nvm/versions/node/v4.2.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/Users/om/.nvm/versions/node/v4.2.1/bin/node" "/Users/om/.nvm/versions/node/v4.2.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/om/.nvm/versions/node/v4.2.1/lib/node_modules/atom-package-manager/node_modules/git-utils
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/om/.nvm/versions/node/v4.2.1/bin/node" "/Users/om/.nvm/versions/node/v4.2.1/bin/npm" "i" "-g" "atom-package-manager"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! keytar@3.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the keytar@3.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the keytar package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls keytar
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/om/npm-debug.log
```
