### ISSUE TITLE
Problem updating

### ISSUE THREAD

**Issue by stramel** [atom/apm#247]
### Steps to Reproduce

1. Open Settings
2. Click 'Updates'
3. Click 'Update All'

**OS:** Ubuntu 14.04
**Atom Version:** 0.170.d7158a2

```console
$ apm -v
apm 0.117.0
npm 1.4.4
node 0.10.33
python 2.7.6
git 1.9.1

$ uname -r
3.13.0-43-generic
```

```console
npm ERR! Error: Attempt to unlock /tmp/d-11508-16870-1xu709t/package.tgz, which hasn't been locked
npm ERR!     at unlock (/usr/local/share/atom/resources/app/apm/node_modules/atom-package-manager/node_modules/npm/lib/cache.js:1304:11)
npm ERR!     at cb (/usr/local/share/atom/resources/app/apm/node_modules/atom-package-manager/node_modules/npm/lib/cache.js:866:5)
npm ERR!     at /usr/local/share/atom/resources/app/apm/node_modules/atom-package-manager/node_modules/npm/lib/cache.js:883:20
npm ERR!     at /usr/local/share/atom/resources/app/apm/node_modules/atom-package-manager/node_modules/npm/lib/cache.js:1290:7
npm ERR!     at /usr/local/share/atom/resources/app/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/lockfile/lockfile.js:167:38
npm ERR!     at OpenReq.Req.done (/usr/local/share/atom/resources/app/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:144:5)
npm ERR!     at OpenReq.done (/usr/local/share/atom/resources/app/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:64:22)
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.13.0-43-generic
npm ERR! command "/usr/local/share/atom/resources/app/apm/node_modules/atom-package-manager/bin/node" "/usr/local/share/atom/resources/app/apm/node_modules/atom-package-manager/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/usr/local/share/atom/resources/app/apm/node_modules/atom-package-manager/.apmrc" "--userconfig" "/home/stramel/.atom/.apmrc" "install" "/tmp/d-11508-16870-1xu709t/package.tgz" "--target=0.20.0" "--arch=x64"
npm ERR! cwd /tmp/apm-install-dir-11508-16870-4cdzbu
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.4
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /tmp/apm-install-dir-11508-16870-4cdzbu/npm-debug.log
npm ERR! not ok code 0
```

**UPDATE:** Can't install any packages anymore.

**Comment by stramel** [comment]
For some reason, I now need to use `sudo` to launch atom and perform package updates/installs? I'm not sure how or why this changed. I use a script to perform the install and never change the repository other than through the script.

**Comment by kevinsawicki** [comment]
Are you still seeing this on the latest version of Atom? The bundled npm version has been upgraded a couple times since you reported this.

**Comment by stramel** [comment]
@kevinsawicki I will double check in the morning

**Comment by stramel** [comment]
@kevinsawicki Yes, I am still having this issue. I'm unsure why it started seeing as I didn't have this issue for most of the time I have been using Atom.

**Comment by stramel** [comment]
@kevinsawicki Apparently, at some point along the way my `.atom` folder was generated by `root` user. I was able to update again by performing the following command:

```console
$ sudo chown -R $(whoami) ~/.atom
```
