### ISSUE TITLE
"apm stars --install" error

### ISSUE THREAD

**Issue by yimingli** [atom/apm#310]
Atom 0.182.0 installed by brew-cask
Mac Yosemite 10.10.2
```
➜  ~  apm -v
apm  0.140.0
npm  2.5.1
node 0.10.35
python 2.7.9
git 2.3.0
```

```
➜  ~  apm stars --install
Installing fancy-new-file to /Users/paul/.atom/packages ✓
Installing highlight-selected to /Users/paul/.atom/packages ✓
Installing indentation-indicator to /Users/paul/.atom/packages ✓
Installing language-r to /Users/paul/.atom/packages ✓
Installing set-syntax to /Users/paul/.atom/packages ✓
Installing tabs-to-spaces to /Users/paul/.atom/packages ✓
Installing term2 to /Users/paul/.atom/packages ✗

> pty.js@0.2.5 install /private/var/folders/3_/n1zj8wfx1yncxcjfty5_gfjm0000gn/T/apm-install-dir-115123-45318-19ssosw/node_modules/term2/node_modules/pty.js
> node-gyp rebuild

  CXX(target) Release/obj.target/pty/src/unix/pty.o

In file included from ../src/unix/pty.cc:16:
../node_modules/nan/nan.h:67:21: error: no type named 'ExternalAsciiStringResource' in 'v8::String'; did you mean 'ExternalStringResource'?
typedef v8::String::ExternalAsciiStringResource
        ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
                    ExternalStringResource
/Users/paul/.atom/.node-gyp/.node-gyp/0.21.0/deps/v8/include/v8.h:1936:19: note: 'ExternalStringResource' declared here
  class V8_EXPORT ExternalStringResource
                  ^
In file included from ../src/unix/pty.cc:16:
In file included from ../node_modules/nan/nan.h:74:
../node_modules/nan/nan_new.h:164:26: error: class member cannot be redeclared
  static inline return_t New(NanExternalOneByteStringResource * value);
                         ^
../node_modules/nan/nan_new.h:163:26: note: previous declaration is here
  static inline return_t New(v8::String::ExternalStringResource * value);
                         ^
In file included from ../src/unix/pty.cc:16:
In file included from ../node_modules/nan/nan.h:74:
In file included from ../node_modules/nan/nan_new.h:190:
../node_modules/nan/nan_implementation_12_inl.h:222:22: error: redefinition of 'New'
Factory<v8::String>::New(NanExternalOneByteStringResource * value) {
                     ^
../node_modules/nan/nan_implementation_12_inl.h:217:22: note: previous definition is here
Factory<v8::String>::New(v8::String::ExternalStringResource * value) {
                     ^
In file included from ../src/unix/pty.cc:16:
In file included from ../node_modules/nan/nan.h:74:
../node_modules/nan/nan_new.h:319:1: error: redefinition of 'NanNew'
NanNew(NanExternalOneByteStringResource * value) {
^
../node_modules/nan/nan_new.h:313:1: note: previous definition is here
NanNew(v8::String::ExternalStringResource * value) {
^
In file included from ../src/unix/pty.cc:16:
../node_modules/nan/nan.h:1790:17: error: no member named 'GetExternalAsciiStringResource' in 'v8::String'; did you mean 'GetExternalOneByteStringResource'?
    return str->GetExternalAsciiStringResource();
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                GetExternalOneByteStringResource
/Users/paul/.atom/.node-gyp/.node-gyp/0.21.0/deps/v8/include/v8.h:2003:40: note: 'GetExternalOneByteStringResource' declared here
  const ExternalOneByteStringResource* GetExternalOneByteStringResource() const;
                                       ^
In file included from ../src/unix/pty.cc:16:
../node_modules/nan/nan.h:1790:12: error: cannot initialize return object of type 'const NanExternalOneByteStringResource *' (aka 'const v8::String::ExternalStringResource *') with an rvalue of type 'const v8::String::ExternalOneByteStringResource *'
    return str->GetExternalAsciiStringResource();
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1800:17: error: no member named 'IsExternalAscii' in 'v8::String'; did you mean 'IsExternal'?
    return str->IsExternalAscii();
                ^~~~~~~~~~~~~~~
                IsExternal
/Users/paul/.atom/.node-gyp/.node-gyp/0.21.0/deps/v8/include/v8.h:1900:8: note: 'IsExternal' declared here
  bool IsExternal() const;
       ^
In file included from ../src/unix/pty.cc:16:
../node_modules/nan/nan.h:1825:11: error: assigning to 'const char *' from incompatible type 'const uint16_t *' (aka 'const unsigned short *')
    *data = ext->data();
          ^ ~~~~~~~~~~~
../node_modules/nan/nan.h:1868:10: error: no matching function for call to 'Encode'
  return node::Encode(
         ^~~~~~~~~~~~
/Users/paul/.atom/.node-gyp/.node-gyp/0.21.0/src/node.h:272:34: note: candidate function not viable: cannot convert argument of incomplete type 'const void *' to 'const char *'
NODE_EXTERN v8::Local<v8::Value> Encode(v8::Isolate* isolate,
                                 ^
/Users/paul/.atom/.node-gyp/.node-gyp/0.21.0/src/node.h:278:34: note: candidate function not viable: requires 3 arguments, but 4 were provided
NODE_EXTERN v8::Local<v8::Value> Encode(v8::Isolate* isolate,
                                 ^
/Users/paul/.atom/.node-gyp/.node-gyp/0.21.0/src/node.h:283:45: note: candidate function not viable: requires at most 3 arguments, but 4 were provided
                inline v8::Local<v8::Value> Encode(
                                            ^
/Users/paul/.atom/.node-gyp/.node-gyp/0.21.0/src/node.h:64:53: note: expanded from macro 'NODE_DEPRECATED'
#define NODE_DEPRECATED(msg, fn) V8_DEPRECATED(msg, fn)
                                                    ^
/Users/paul/.atom/.node-gyp/.node-gyp/0.21.0/deps/v8/include/v8config.h:329:45: note: expanded from macro 'V8_DEPRECATED'
# define V8_DEPRECATED(message, declarator) declarator
                                            ^
9 errors generated.
make: *** [Release/obj.target/pty/src/unix/pty.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/3_/n1zj8wfx1yncxcjfty5_gfjm0000gn/T/apm-install-dir-115123-45318-19ssosw/node_modules/term2/node_modules/pty.js
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Darwin 14.1.0
npm ERR! argv "/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/apm/bin/node" "/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/paul/.atom/.apm/.apmrc" "--userconfig" "/Users/paul/.atom/.apmrc" "install" "/private/var/folders/3_/n1zj8wfx1yncxcjfty5_gfjm0000gn/T/d-115123-45318-ztqqcr/package.tgz" "--target=0.21.0" "--arch=x64"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.2.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pty.js@0.2.5 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/3_/n1zj8wfx1yncxcjfty5_gfjm0000gn/T/apm-install-dir-115123-45318-19ssosw/npm-debug.log
```

**Comment by yimingli** [comment]
The problem seems to be the package `term2`. I'm closing this.
