### ISSUE TITLE
apm help publish crashes

### ISSUE THREAD

**Issue by tinloaf** [atom/apm#332]
I'm using atom from current git, i.e.: 

```
tinloaf@janeway acp-python-jedi % apm -v          
apm  0.152.0
npm  2.5.1
node 0.10.35
python 3.3.5
git 2.0.5
```

This happens when I try to get help on publish:

```
tinloaf@janeway acp-python-jedi % apm help publish

/home/tinloaf/opt/atom/share/atom/resources/app/apm/lib/apm-cli.js:217
            return new Command().showHelp(options.commandArgs);
                                 ^
TypeError: Object #<Publish> has no method 'showHelp'
    at Object.module.exports.run (/home/tinloaf/opt/atom/share/atom/resources/app/apm/lib/apm-cli.js:217:34)
    at Object.<anonymous> (/home/tinloaf/opt/atom/share/atom/resources/app/apm/lib/cli.js:6:7)
    at Object.<anonymous> (/home/tinloaf/opt/atom/share/atom/resources/app/apm/lib/cli.js:17:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
```

**Comment by Fank** [comment]
Confirmed:

>apm help publish

c:\Users\Fank\AppData\Local\atom\app-0.188.0\resources\app\apm\lib\apm-cli.js:217
            return new Command().showHelp(options.commandArgs);
                                 ^
TypeError: Object #<Publish> has no method 'showHelp'
    at Object.module.exports.run (c:\Users\Fank\AppData\Local\atom\app-0.188.0\resources\app\apm\lib\apm-cli.js:217:34)
    at Object.<anonymous> (c:\Users\Fank\AppData\Local\atom\app-0.188.0\resources\app\apm\lib\cli.js:6:7)
    at Object.<anonymous> (c:\Users\Fank\AppData\Local\atom\app-0.188.0\resources\app\apm\lib\cli.js:17:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
>

**Comment by kevinsawicki** [comment]
Thanks for reporting this, fixed on atom/atom master now.
