### ISSUE TITLE
apm install fails for any package. Fails with ECONNREFUSED

### ISSUE THREAD

**Issue by nirrek** [atom/apm#485]
Any package that I attempt to install using apm fails. Version info and a verbose error output can be seen below.

I have three macs all on the same network and this error is occurring only on two of them (both running OSX 10.10.5). The error does not occur on the one running OSX 10.11.2. I am also not behind a proxy.

### OS
`OSX 10.10.5`

### apm version information
```bash
$ apm -v
apm  1.4.1
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.2.1
```

### Error output
```bash
$ apm install pigments --verbose
Installing pigments to /Users/nirrek/.atom/packages REQUEST { url: 'https://atom.io/api/packages/pigments',
  json: true,
  retries: 4,
  proxy: null,
  strictSSL: true,
  headers: { 'User-Agent': 'npm/2.13.3 node/v0.10.40 darwin x64' },
  callback: [Function],
  method: 'GET' }
REQUEST make request https://atom.io/api/packages/pigments
REQUEST onRequestResponse https://atom.io/api/packages/pigments 200 { server: 'Cowboy',
  connection: 'close',
  date: 'Tue, 05 Jan 2016 01:45:54 GMT',
  status: '200 OK',
  'strict-transport-security': 'max-age=631152000',
  'x-frame-options': 'DENY',
  'x-xss-protection': '1; mode=block',
  'x-content-type-options': 'nosniff',
  'content-security-policy': 'default-src \'self\'; connect-src \'self\'; font-src \'self\'; frame-src \'self\' https://www.youtube.com; img-src https://* \'self\' data:; media-src \'none\'; object-src \'self\'; script-src \'self\' \'unsafe-inline\' https://ssl.google-analytics.com https://www.google-analytics.com https://platform.twitter.com; style-src \'self\' \'unsafe-inline\';',
  'content-type': 'application/json; charset=utf-8',
  etag: 'W/"3bd71e58c89c6f800c3f6e96f72906f3"',
  'cache-control': 'max-age=0, private, must-revalidate',
  'x-request-id': '99a2b8ed-eadc-4828-8f76-5142e2e21abb',
  'x-runtime': '0.021084',
  'x-rack-cache': 'miss',
  vary: 'Origin',
  via: '1.1 vegur' }
REQUEST finish init function https://atom.io/api/packages/pigments
REQUEST response end https://atom.io/api/packages/pigments 200 { server: 'Cowboy',
  connection: 'close',
  date: 'Tue, 05 Jan 2016 01:45:54 GMT',
  status: '200 OK',
  'strict-transport-security': 'max-age=631152000',
  'x-frame-options': 'DENY',
  'x-xss-protection': '1; mode=block',
  'x-content-type-options': 'nosniff',
  'content-security-policy': 'default-src \'self\'; connect-src \'self\'; font-src \'self\'; frame-src \'self\' https://www.youtube.com; img-src https://* \'self\' data:; media-src \'none\'; object-src \'self\'; script-src \'self\' \'unsafe-inline\' https://ssl.google-analytics.com https://www.google-analytics.com https://platform.twitter.com; style-src \'self\' \'unsafe-inline\';',
  'content-type': 'application/json; charset=utf-8',
  etag: 'W/"3bd71e58c89c6f800c3f6e96f72906f3"',
  'cache-control': 'max-age=0, private, must-revalidate',
  'x-request-id': '99a2b8ed-eadc-4828-8f76-5142e2e21abb',
  'x-runtime': '0.021084',
  'x-rack-cache': 'miss',
  vary: 'Origin',
  via: '1.1 vegur' }
REQUEST end event https://atom.io/api/packages/pigments
REQUEST has body https://atom.io/api/packages/pigments 53880
REQUEST emitting complete https://atom.io/api/packages/pigments
REQUEST { url: 'https://www.atom.io/api/packages/pigments/versions/0.19.5/tarball',
  proxy: null,
  strictSSL: true,
  headers: { 'User-Agent': 'npm/2.13.3 node/v0.10.40 darwin x64' },
  method: 'GET',
  callback: undefined }
REQUEST make request https://www.atom.io/api/packages/pigments/versions/0.19.5/tarball
REQUEST onRequestResponse https://www.atom.io/api/packages/pigments/versions/0.19.5/tarball 302 { server: 'Cowboy',
  connection: 'close',
  date: 'Tue, 05 Jan 2016 01:45:56 GMT',
  status: '302 Found',
  'strict-transport-security': 'max-age=631152000',
  'x-frame-options': 'DENY',
  'x-xss-protection': '1; mode=block',
  'x-content-type-options': 'nosniff',
  'content-security-policy': 'default-src \'self\'; connect-src \'self\'; font-src \'self\'; frame-src \'self\' https://www.youtube.com; img-src https://* \'self\' data:; media-src \'none\'; object-src \'self\'; script-src \'self\' \'unsafe-inline\' https://ssl.google-analytics.com https://www.google-analytics.com https://platform.twitter.com; style-src \'self\' \'unsafe-inline\';',
  location: 'https://codeload.github.com/abe33/atom-pigments/legacy.tar.gz/v0.19.5',
  'content-type': 'text/html; charset=utf-8',
  'cache-control': 'no-cache',
  'x-request-id': '245cf5c8-edde-42e8-8c1b-ff311d154d4d',
  'x-runtime': '0.076120',
  'x-rack-cache': 'miss',
  vary: 'Origin',
  via: '1.1 vegur' }
REQUEST redirect https://codeload.github.com/abe33/atom-pigments/legacy.tar.gz/v0.19.5
REQUEST redirect to https://codeload.github.com/abe33/atom-pigments/legacy.tar.gz/v0.19.5
REQUEST {}
REQUEST make request https://codeload.github.com/abe33/atom-pigments/legacy.tar.gz/v0.19.5
REQUEST response end https://codeload.github.com/abe33/atom-pigments/legacy.tar.gz/v0.19.5 302 { server: 'Cowboy',
  connection: 'close',
  date: 'Tue, 05 Jan 2016 01:45:56 GMT',
  status: '302 Found',
  'strict-transport-security': 'max-age=631152000',
  'x-frame-options': 'DENY',
  'x-xss-protection': '1; mode=block',
  'x-content-type-options': 'nosniff',
  'content-security-policy': 'default-src \'self\'; connect-src \'self\'; font-src \'self\'; frame-src \'self\' https://www.youtube.com; img-src https://* \'self\' data:; media-src \'none\'; object-src \'self\'; script-src \'self\' \'unsafe-inline\' https://ssl.google-analytics.com https://www.google-analytics.com https://platform.twitter.com; style-src \'self\' \'unsafe-inline\';',
  location: 'https://codeload.github.com/abe33/atom-pigments/legacy.tar.gz/v0.19.5',
  'content-type': 'text/html; charset=utf-8',
  'cache-control': 'no-cache',
  'x-request-id': '245cf5c8-edde-42e8-8c1b-ff311d154d4d',
  'x-runtime': '0.076120',
  'x-rack-cache': 'miss',
  vary: 'Origin',
  via: '1.1 vegur' }
REQUEST onRequestResponse https://codeload.github.com/abe33/atom-pigments/legacy.tar.gz/v0.19.5 200 { 'content-length': '4914916',
  'access-control-allow-origin': 'https://render.githubusercontent.com',
  'content-security-policy': 'default-src \'none\'',
  'x-xss-protection': '1; mode=block',
  'x-frame-options': 'deny',
  'x-content-type-options': 'nosniff',
  'strict-transport-security': 'max-age=31536000',
  vary: 'Authorization,Accept-Encoding',
  etag: '"fda0f3c3a9027fd9255372ae6d4c408b41ed0beb"',
  'content-type': 'application/x-gzip',
  'content-disposition': 'attachment; filename=abe33-atom-pigments-v0.19.5-0-gfda0f3c.tar.gz',
  date: 'Tue, 05 Jan 2016 01:45:58 GMT',
  'x-github-request-id': '0ECA085F:35CD:465E8962:568B2055' }
REQUEST finish init function https://codeload.github.com/abe33/atom-pigments/legacy.tar.gz/v0.19.5
REQUEST response end https://codeload.github.com/abe33/atom-pigments/legacy.tar.gz/v0.19.5 200 { 'content-length': '4914916',
  'access-control-allow-origin': 'https://render.githubusercontent.com',
  'content-security-policy': 'default-src \'none\'',
  'x-xss-protection': '1; mode=block',
  'x-frame-options': 'deny',
  'x-content-type-options': 'nosniff',
  'strict-transport-security': 'max-age=31536000',
  vary: 'Authorization,Accept-Encoding',
  etag: '"fda0f3c3a9027fd9255372ae6d4c408b41ed0beb"',
  'content-type': 'application/x-gzip',
  'content-disposition': 'attachment; filename=abe33-atom-pigments-v0.19.5-0-gfda0f3c.tar.gz',
  date: 'Tue, 05 Jan 2016 01:45:58 GMT',
  'x-github-request-id': '0ECA085F:35CD:465E8962:568B2055' }
gyp info it worked if it ends with ok
gyp verb cli [ '/Applications/Atom.app/Contents/Resources/app/apm/bin/node',
gyp verb cli   '/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'install',
gyp verb cli   '--target=0.34.3',
gyp verb cli   '--dist-url=https://atom.io/download/atom-shell',
gyp verb cli   '--arch=x64',
gyp verb cli   '--ensure',
gyp verb cli   '--verbose' ]
gyp info using node-gyp@2.0.2
gyp info using node@0.10.40 | darwin | x64
gyp verb command install []
gyp verb install input version string "0.34.3"
gyp verb install installing version: 0.34.3
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 0.34.3
gyp verb ensuring nodedir is created /Users/nirrek/.atom/.node-gyp/.node-gyp/0.34.3
gyp verb created nodedir /Users/nirrek/.atom/.node-gyp/.node-gyp/0.34.3
gyp http GET https://atom.io/download/atom-shell/v0.34.3/node-v0.34.3.tar.gz
REQUEST { uri: 'https://atom.io/download/atom-shell/v0.34.3/node-v0.34.3.tar.gz',
  headers: { 'User-Agent': 'node-gyp v2.0.2 (node v0.10.40)' },
  callback: undefined }
REQUEST make request https://atom.io/download/atom-shell/v0.34.3/node-v0.34.3.tar.gz
REQUEST onRequestResponse https://atom.io/download/atom-shell/v0.34.3/node-v0.34.3.tar.gz 302 { server: 'Cowboy',
  connection: 'close',
  date: 'Tue, 05 Jan 2016 01:46:02 GMT',
  status: '302 Found',
  'strict-transport-security': 'max-age=631152000',
  'x-frame-options': 'DENY',
  'x-xss-protection': '1; mode=block',
  'x-content-type-options': 'nosniff',
  'content-security-policy': 'default-src \'self\'; connect-src \'self\'; font-src \'self\'; frame-src \'self\' https://www.youtube.com; img-src https://* \'self\' data:; media-src \'none\'; object-src \'self\'; script-src \'self\' \'unsafe-inline\' https://ssl.google-analytics.com https://www.google-analytics.com https://platform.twitter.com; style-src \'self\' \'unsafe-inline\';',
  location: 'http://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v0.34.3/node-v0.34.3.tar.gz',
  'content-type': 'text/html; charset=utf-8',
  'cache-control': 'no-cache',
  'x-request-id': '0199dc8b-debf-4f57-84ca-979bc6463148',
  'x-runtime': '0.016491',
  'x-rack-cache': 'miss',
  via: '1.1 vegur' }
REQUEST redirect http://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v0.34.3/node-v0.34.3.tar.gz
REQUEST redirect to http://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v0.34.3/node-v0.34.3.tar.gz
REQUEST {}
REQUEST response end http://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v0.34.3/node-v0.34.3.tar.gz 302 { server: 'Cowboy',
  connection: 'close',
  date: 'Tue, 05 Jan 2016 01:46:02 GMT',
  status: '302 Found',
  'strict-transport-security': 'max-age=631152000',
  'x-frame-options': 'DENY',
  'x-xss-protection': '1; mode=block',
  'x-content-type-options': 'nosniff',
  'content-security-policy': 'default-src \'self\'; connect-src \'self\'; font-src \'self\'; frame-src \'self\' https://www.youtube.com; img-src https://* \'self\' data:; media-src \'none\'; object-src \'self\'; script-src \'self\' \'unsafe-inline\' https://ssl.google-analytics.com https://www.google-analytics.com https://platform.twitter.com; style-src \'self\' \'unsafe-inline\';',
  location: 'http://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v0.34.3/node-v0.34.3.tar.gz',
  'content-type': 'text/html; charset=utf-8',
  'cache-control': 'no-cache',
  'x-request-id': '0199dc8b-debf-4f57-84ca-979bc6463148',
  'x-runtime': '0.016491',
  'x-rack-cache': 'miss',
  via: '1.1 vegur' }
REQUEST make request http://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v0.34.3/node-v0.34.3.tar.gz
gyp WARN install got an error, rolling back install
gyp verb command remove [ '0.34.3' ]
gyp verb remove using node-gyp dir: /Users/nirrek/.atom/.node-gyp/.node-gyp
gyp verb remove removing target version: 0.34.3
gyp verb remove removing development files for version: 0.34.3
gyp ERR! install error 
gyp ERR! stack Error: connect ECONNREFUSED
gyp ERR! stack     at errnoException (net.js:905:11)
gyp ERR! stack     at Object.afterConnect [as oncomplete] (net.js:896:19)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "install" "--target=0.34.3" "--dist-url=https://atom.io/download/atom-shell" "--arch=x64" "--ensure" "--verbose"
gyp ERR! cwd /Users/nirrek/.atom
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
```

**Comment by lee-dohm** [comment]
Can you reproduce this error on the [tabs-to-spaces package](https://atom.io/packages/tabs-to-spaces)?

**Comment by nirrek** [comment]
Yep, see logs below. I tried with all the featured packages on here https://atom.io/packages as well. They all fail with the same error.

```bash
$ apm install tabs-to-spaces --verbose
Installing tabs-to-spaces to /Users/nirrek/.atom/packages REQUEST { url: 'https://atom.io/api/packages/tabs-to-spaces',
  json: true,
  retries: 4,
  proxy: null,
  strictSSL: true,
  headers: { 'User-Agent': 'npm/2.13.3 node/v0.10.40 darwin x64' },
  callback: [Function],
  method: 'GET' }
REQUEST make request https://atom.io/api/packages/tabs-to-spaces
REQUEST onRequestResponse https://atom.io/api/packages/tabs-to-spaces 200 { server: 'Cowboy',
  connection: 'close',
  date: 'Fri, 08 Jan 2016 01:33:56 GMT',
  status: '200 OK',
  'strict-transport-security': 'max-age=631152000',
  'x-frame-options': 'DENY',
  'x-xss-protection': '1; mode=block',
  'x-content-type-options': 'nosniff',
  'content-security-policy': 'default-src \'self\'; connect-src \'self\'; font-src \'self\'; frame-src \'self\' https://www.youtube.com; img-src https://* \'self\' data:; media-src \'none\'; object-src \'self\'; script-src \'self\' \'unsafe-inline\' https://ssl.google-analytics.com https://www.google-analytics.com https://platform.twitter.com; style-src \'self\' \'unsafe-inline\';',
  'content-type': 'application/json; charset=utf-8',
  etag: 'W/"4eb1862aeb23761f317e53f0677359e8"',
  'cache-control': 'max-age=0, private, must-revalidate',
  'x-request-id': '6251e61c-1aa2-43aa-ab72-ce61c3e813bb',
  'x-runtime': '0.030236',
  'x-rack-cache': 'miss',
  vary: 'Origin',
  via: '1.1 vegur' }
REQUEST finish init function https://atom.io/api/packages/tabs-to-spaces
REQUEST response end https://atom.io/api/packages/tabs-to-spaces 200 { server: 'Cowboy',
  connection: 'close',
  date: 'Fri, 08 Jan 2016 01:33:56 GMT',
  status: '200 OK',
  'strict-transport-security': 'max-age=631152000',
  'x-frame-options': 'DENY',
  'x-xss-protection': '1; mode=block',
  'x-content-type-options': 'nosniff',
  'content-security-policy': 'default-src \'self\'; connect-src \'self\'; font-src \'self\'; frame-src \'self\' https://www.youtube.com; img-src https://* \'self\' data:; media-src \'none\'; object-src \'self\'; script-src \'self\' \'unsafe-inline\' https://ssl.google-analytics.com https://www.google-analytics.com https://platform.twitter.com; style-src \'self\' \'unsafe-inline\';',
  'content-type': 'application/json; charset=utf-8',
  etag: 'W/"4eb1862aeb23761f317e53f0677359e8"',
  'cache-control': 'max-age=0, private, must-revalidate',
  'x-request-id': '6251e61c-1aa2-43aa-ab72-ce61c3e813bb',
  'x-runtime': '0.030236',
  'x-rack-cache': 'miss',
  vary: 'Origin',
  via: '1.1 vegur' }
REQUEST end event https://atom.io/api/packages/tabs-to-spaces
REQUEST has body https://atom.io/api/packages/tabs-to-spaces 17376
REQUEST emitting complete https://atom.io/api/packages/tabs-to-spaces
REQUEST { url: 'https://www.atom.io/api/packages/tabs-to-spaces/versions/1.0.1/tarball',
  proxy: null,
  strictSSL: true,
  headers: { 'User-Agent': 'npm/2.13.3 node/v0.10.40 darwin x64' },
  method: 'GET',
  callback: undefined }
REQUEST make request https://www.atom.io/api/packages/tabs-to-spaces/versions/1.0.1/tarball
REQUEST onRequestResponse https://www.atom.io/api/packages/tabs-to-spaces/versions/1.0.1/tarball 302 { server: 'Cowboy',
  connection: 'close',
  date: 'Fri, 08 Jan 2016 01:33:57 GMT',
  status: '302 Found',
  'strict-transport-security': 'max-age=631152000',
  'x-frame-options': 'DENY',
  'x-xss-protection': '1; mode=block',
  'x-content-type-options': 'nosniff',
  'content-security-policy': 'default-src \'self\'; connect-src \'self\'; font-src \'self\'; frame-src \'self\' https://www.youtube.com; img-src https://* \'self\' data:; media-src \'none\'; object-src \'self\'; script-src \'self\' \'unsafe-inline\' https://ssl.google-analytics.com https://www.google-analytics.com https://platform.twitter.com; style-src \'self\' \'unsafe-inline\';',
  location: 'https://codeload.github.com/lee-dohm/tabs-to-spaces/legacy.tar.gz/v1.0.1',
  'content-type': 'text/html; charset=utf-8',
  'cache-control': 'no-cache',
  'x-request-id': '25e33a1c-c0cc-4b6f-8e6d-f4020db1cd18',
  'x-runtime': '0.129053',
  'x-rack-cache': 'miss',
  vary: 'Origin',
  via: '1.1 vegur' }
REQUEST redirect https://codeload.github.com/lee-dohm/tabs-to-spaces/legacy.tar.gz/v1.0.1
REQUEST redirect to https://codeload.github.com/lee-dohm/tabs-to-spaces/legacy.tar.gz/v1.0.1
REQUEST {}
REQUEST make request https://codeload.github.com/lee-dohm/tabs-to-spaces/legacy.tar.gz/v1.0.1
REQUEST response end https://codeload.github.com/lee-dohm/tabs-to-spaces/legacy.tar.gz/v1.0.1 302 { server: 'Cowboy',
  connection: 'close',
  date: 'Fri, 08 Jan 2016 01:33:57 GMT',
  status: '302 Found',
  'strict-transport-security': 'max-age=631152000',
  'x-frame-options': 'DENY',
  'x-xss-protection': '1; mode=block',
  'x-content-type-options': 'nosniff',
  'content-security-policy': 'default-src \'self\'; connect-src \'self\'; font-src \'self\'; frame-src \'self\' https://www.youtube.com; img-src https://* \'self\' data:; media-src \'none\'; object-src \'self\'; script-src \'self\' \'unsafe-inline\' https://ssl.google-analytics.com https://www.google-analytics.com https://platform.twitter.com; style-src \'self\' \'unsafe-inline\';',
  location: 'https://codeload.github.com/lee-dohm/tabs-to-spaces/legacy.tar.gz/v1.0.1',
  'content-type': 'text/html; charset=utf-8',
  'cache-control': 'no-cache',
  'x-request-id': '25e33a1c-c0cc-4b6f-8e6d-f4020db1cd18',
  'x-runtime': '0.129053',
  'x-rack-cache': 'miss',
  vary: 'Origin',
  via: '1.1 vegur' }
REQUEST onRequestResponse https://codeload.github.com/lee-dohm/tabs-to-spaces/legacy.tar.gz/v1.0.1 200 { 'content-length': '83484',
  'access-control-allow-origin': 'https://render.githubusercontent.com',
  'content-security-policy': 'default-src \'none\'',
  'x-xss-protection': '1; mode=block',
  'x-frame-options': 'deny',
  'x-content-type-options': 'nosniff',
  'strict-transport-security': 'max-age=31536000',
  vary: 'Authorization,Accept-Encoding',
  etag: '"4096342abce7d2d29953cb8ec587d96c101256d3"',
  'content-type': 'application/x-gzip',
  'content-disposition': 'attachment; filename=lee-dohm-tabs-to-spaces-v1.0.1-0-g4096342.tar.gz',
  date: 'Fri, 08 Jan 2016 01:33:59 GMT',
  'x-github-request-id': '0ECA085F:30F5:1B248:568F1206' }
REQUEST finish init function https://codeload.github.com/lee-dohm/tabs-to-spaces/legacy.tar.gz/v1.0.1
REQUEST response end https://codeload.github.com/lee-dohm/tabs-to-spaces/legacy.tar.gz/v1.0.1 200 { 'content-length': '83484',
  'access-control-allow-origin': 'https://render.githubusercontent.com',
  'content-security-policy': 'default-src \'none\'',
  'x-xss-protection': '1; mode=block',
  'x-frame-options': 'deny',
  'x-content-type-options': 'nosniff',
  'strict-transport-security': 'max-age=31536000',
  vary: 'Authorization,Accept-Encoding',
  etag: '"4096342abce7d2d29953cb8ec587d96c101256d3"',
  'content-type': 'application/x-gzip',
  'content-disposition': 'attachment; filename=lee-dohm-tabs-to-spaces-v1.0.1-0-g4096342.tar.gz',
  date: 'Fri, 08 Jan 2016 01:33:59 GMT',
  'x-github-request-id': '0ECA085F:30F5:1B248:568F1206' }
gyp info it worked if it ends with ok
gyp verb cli [ '/Applications/Atom.app/Contents/Resources/app/apm/bin/node',
gyp verb cli   '/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'install',
gyp verb cli   '--target=0.34.3',
gyp verb cli   '--dist-url=https://atom.io/download/atom-shell',
gyp verb cli   '--arch=x64',
gyp verb cli   '--ensure',
gyp verb cli   '--verbose' ]
gyp info using node-gyp@2.0.2
gyp info using node@0.10.40 | darwin | x64
gyp verb command install []
gyp verb install input version string "0.34.3"
gyp verb install installing version: 0.34.3
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 0.34.3
gyp verb ensuring nodedir is created /Users/nirrek/.atom/.node-gyp/.node-gyp/0.34.3
gyp verb created nodedir /Users/nirrek/.atom/.node-gyp/.node-gyp/0.34.3
gyp http GET https://atom.io/download/atom-shell/v0.34.3/node-v0.34.3.tar.gz
REQUEST { uri: 'https://atom.io/download/atom-shell/v0.34.3/node-v0.34.3.tar.gz',
  headers: { 'User-Agent': 'node-gyp v2.0.2 (node v0.10.40)' },
  callback: undefined }
REQUEST make request https://atom.io/download/atom-shell/v0.34.3/node-v0.34.3.tar.gz
REQUEST onRequestResponse https://atom.io/download/atom-shell/v0.34.3/node-v0.34.3.tar.gz 302 { server: 'Cowboy',
  connection: 'close',
  date: 'Fri, 08 Jan 2016 01:34:01 GMT',
  status: '302 Found',
  'strict-transport-security': 'max-age=631152000',
  'x-frame-options': 'DENY',
  'x-xss-protection': '1; mode=block',
  'x-content-type-options': 'nosniff',
  'content-security-policy': 'default-src \'self\'; connect-src \'self\'; font-src \'self\'; frame-src \'self\' https://www.youtube.com; img-src https://* \'self\' data:; media-src \'none\'; object-src \'self\'; script-src \'self\' \'unsafe-inline\' https://ssl.google-analytics.com https://www.google-analytics.com https://platform.twitter.com; style-src \'self\' \'unsafe-inline\';',
  location: 'http://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v0.34.3/node-v0.34.3.tar.gz',
  'content-type': 'text/html; charset=utf-8',
  'cache-control': 'no-cache',
  'x-request-id': '280001f5-b2af-4c15-bd5a-4639464a31ae',
  'x-runtime': '0.022195',
  'x-rack-cache': 'miss',
  via: '1.1 vegur' }
REQUEST redirect http://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v0.34.3/node-v0.34.3.tar.gz
REQUEST redirect to http://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v0.34.3/node-v0.34.3.tar.gz
REQUEST {}
REQUEST make request http://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v0.34.3/node-v0.34.3.tar.gz
REQUEST response end http://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v0.34.3/node-v0.34.3.tar.gz 302 { server: 'Cowboy',
  connection: 'close',
  date: 'Fri, 08 Jan 2016 01:34:01 GMT',
  status: '302 Found',
  'strict-transport-security': 'max-age=631152000',
  'x-frame-options': 'DENY',
  'x-xss-protection': '1; mode=block',
  'x-content-type-options': 'nosniff',
  'content-security-policy': 'default-src \'self\'; connect-src \'self\'; font-src \'self\'; frame-src \'self\' https://www.youtube.com; img-src https://* \'self\' data:; media-src \'none\'; object-src \'self\'; script-src \'self\' \'unsafe-inline\' https://ssl.google-analytics.com https://www.google-analytics.com https://platform.twitter.com; style-src \'self\' \'unsafe-inline\';',
  location: 'http://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v0.34.3/node-v0.34.3.tar.gz',
  'content-type': 'text/html; charset=utf-8',
  'cache-control': 'no-cache',
  'x-request-id': '280001f5-b2af-4c15-bd5a-4639464a31ae',
  'x-runtime': '0.022195',
  'x-rack-cache': 'miss',
  via: '1.1 vegur' }
gyp WARN install got an error, rolling back install
gyp verb command remove [ '0.34.3' ]
gyp verb remove using node-gyp dir: /Users/nirrek/.atom/.node-gyp/.node-gyp
gyp verb remove removing target version: 0.34.3
gyp verb remove removing development files for version: 0.34.3
gyp ERR! install error 
gyp ERR! stack Error: connect ECONNREFUSED
gyp ERR! stack     at errnoException (net.js:905:11)
gyp ERR! stack     at Object.afterConnect [as oncomplete] (net.js:896:19)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "install" "--target=0.34.3" "--dist-url=https://atom.io/download/atom-shell" "--arch=x64" "--ensure" "--verbose"
gyp ERR! cwd /Users/nirrek/.atom
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
```
