### ISSUE TITLE
apm test fails if ~/github/atom or ~/github/Atom is present.

### ISSUE THREAD

**Issue by peterhal** [atom/apm#487]
To repro:

rm -rf ~/github

Run 'apm test' on any Atom package successfully.

mkdir -p ~/github/atom

See apm test fail with:

2016-01-07 13:54:09.026 Atom[24886:124474] Cannot find module '/Users/peterhal/github/atom/src/browser/atom-application'
2016-01-07 13:54:09.031 Atom[24886:124474] Error: Cannot find module '/Users/peterhal/github/atom/src/browser/atom-application'
    at Function.Module._resolveFilename (module.js:334:15)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/browser/main.js:54:25)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)

Expected:

apm test should continue to run as expected.

**Comment by peterhal** [comment]
The cause of this is that apm test call 'atom --dev --test --spec-directory=...'. The presence of '--dev' causes atom report the above error and then hang (or at least not terminate).

2 suggestions:

1) apm test should only add the --dev option if the user opts in, not the default.
2) When the --dev option is specified and Atom cannot find the source directory, give a resonable error message.

**Comment by thedaniel** [comment]
Alternative solution: apm test could be deprecated entirely in favor of running `atom --test` directly.
