### ISSUE TITLE
"apm publish minor" returns TypeError:Object

### ISSUE THREAD

**Issue by bretth18** [atom/apm#493]
Little confused here, been trying to publish an atom package since last night, figured I would try again this morning, still no luck after tinkering around for a few hours. Couldn't find a similar issue.

```
$ apm publish minor

TypeError: Object #<Object> has no method 'replace'
    at Object.module.exports.getRepository (/Applications/Atom.app/Contents/Resources/app/apm/lib/packages.js:13:41)
    at /Applications/Atom.app/Contents/Resources/app/apm/lib/publish.js:156:39
    at /Applications/Atom.app/Contents/Resources/app/apm/lib/publish.js:136:20
    at Request._callback (/Applications/Atom.app/Contents/Resources/app/apm/lib/request.js:59:22)
    at Request.self.callback (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/request/request.js:198:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/request/request.js:1057:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/request/request.js:1003:12)
    at IncomingMessage.emit (events.js:117:20)
```

**Comment by mnquintana** [comment]
What version of Atom are you using?

**Comment by bretth18** [comment]
1.4.0

**Comment by thedaniel** [comment]
What does your package.json look like? Can you link to the repo?

**Comment by bretth18** [comment]
Repo is here: https://github.com/bretth18/dirtySprite-syntax

here's my package.json: 
```
{
	"name": "dirtySprite-syntax",
	"version": "0.0.1",
	"description": "dirtySprite for your dirty code",
	"keywords": [
		"syntax",
		"theme"
	],
	"license": "MIT",
	"repository": {},
	"engines": {
		"atom": ">=1.0.0 <2.0.0"
	},
	"theme": "syntax"
}
```
