### ISSUE TITLE
`apm rebuild` fails on fsevents

### ISSUE THREAD

**Issue by hedefalk** [atom/apm#531]
```
mkdir fsevents-apm-rebuild
cd fsevents-apm-rebuild
apm init --package .
npm install -s fsevents
apm rebuild
```

This consistently fails for me with 

```
Rebuilding modules ✗
node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: Unsupported target version: 0.34.5
node-pre-gyp ERR! stack     at get_runtime_abi (/Users/viktor/dev/projects/fs-events-apm-rebuild/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/versioning.js:156:23)
node-pre-gyp ERR! stack     at Object.module.exports.evaluate (/Users/viktor/dev/projects/fs-events-apm-rebuild/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/versioning.js:265:19)
node-pre-gyp ERR! stack     at install (/Users/viktor/dev/projects/fs-events-apm-rebuild/node_modules/fsevents/node_modules/node-pre-gyp/lib/install.js:138:31)
node-pre-gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (/Users/viktor/dev/projects/fs-events-apm-rebuild/node_modules/fsevents/node_modules/node-pre-gyp/lib/node-pre-gyp.js:48:37)
node-pre-gyp ERR! stack     at run (/Users/viktor/dev/projects/fs-events-apm-rebuild/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp:79:30)
node-pre-gyp ERR! stack     at Object.<anonymous> (/Users/viktor/dev/projects/fs-events-apm-rebuild/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp:131:1)
node-pre-gyp ERR! stack     at Module._compile (module.js:456:26)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:474:10)
node-pre-gyp ERR! stack     at Module.load (module.js:356:32)
node-pre-gyp ERR! stack     at Function.Module._load (module.js:312:12)
node-pre-gyp ERR! System Darwin 15.3.0
node-pre-gyp ERR! command "node" "/Users/viktor/dev/projects/fs-events-apm-rebuild/node_modules/fsevents/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/viktor/dev/projects/fs-events-apm-rebuild/node_modules/fsevents
node-pre-gyp ERR! node -v v0.10.40
node-pre-gyp ERR! node-pre-gyp -v v0.6.24
node-pre-gyp ERR! not ok

npm ERR! Darwin 15.3.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/viktor/.atom/.apm/.apmrc" "--userconfig" "/Users/viktor/.atom/.apmrc" "rebuild" "--target=0.34.5" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE
npm ERR! fsevents@1.0.9 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fsevents@1.0.9 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the fsevents package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls fsevents
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/viktor/dev/projects/fs-events-apm-rebuild/npm-debug.log
```

**Comment by hedefalk** [comment]
This is still not working. There seems to be so much confusion on what '--target' actually refers to. 

To me, apm is just broken, why isn't everyone hitting this?

My fix https://github.com/hedefalk/apm/commit/454b237ab1673279c4520cc80e921f5e45b814d5 has been working so far but now I get 404 weirdness where it seems electron version is used as node version:



```
~/d/p/atom-ensime ❯❯❯ "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/viktor/.atom/.apm/.apmrc" "--userconfig" "/Users/viktor/.atom/.apmrc" "rebuild" "--runtime=electron" "--target=0.36.8" "--arch=x64"

> fsevents@1.0.12 install /Users/viktor/dev/projects/atom-ensime/node_modules/ensime-client/node_modules/chokidar/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: 404 response downloading https://nodejs.org/dist/v0.36.8/node-v0.36.8.tar.gz
gyp ERR! stack     at Request.<anonymous> (/Users/viktor/.nvm/versions/node/v4.2.6/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:244:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onRequestResponse (/Users/viktor/.nvm/versions/node/v4.2.6/lib/node_modules/npm/node_modules/request/request.js:998:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:414:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:304:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Darwin 15.5.0
```

I simply cannot run anything using fsevents on atom right now and I have no idea how to fix it. Again.

**Comment by hedefalk** [comment]
Also, Atom caches incompatible modules very badly so once it has gone bad, it's always bad it seems. Note to self:

global.localStorage.clear("installed-packages:Ensime:0.38.1:electron-0.36.8:incompatible-native-modules");

**Comment by NicolasVanhecke** [comment]
Dis you found a solution to this yet? Even if I have to ditch Atom.
I cannot do anything anymore on any of my projects for a week now. I don't care if I cannot use Atom anymore. Thing is I uninstalled all files and everything related to atom, still can't `npm install`. Not even on old projects that has nothing to do with it.
