### ISSUE TITLE
Error when installing the package

### ISSUE THREAD

**Issue by asael-silva** [atom/apm#581]
I was trying to install this package so I could install an RST package I want to use but it also fails the same way. Before you ask, I am using Windows 7 as administrator, I have installed GitHub prior to testing this install.

Follows the error message:

Installing “atom-package-manager@1.9.3” failed.Hide output…

> keytar@3.0.2 install C:\Users\Felix\AppData\Local\Temp\apm-install-dir-116521-2936-1yk1132\node_modules\atom-package-manager\node_modules\keytar
> node-gyp rebuild

C:\Users\Felix\AppData\Local\Temp\apm-install-dir-116521-2936-1yk1132\node_modules\atom-package-manager\node_modules\keytar>if not defined npm_config_node_gyp (node "C:\Users\Felix\AppData\Local\atom\app-1.8.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild ) 

> oniguruma@5.1.2 install C:\Users\Felix\AppData\Local\Temp\apm-install-dir-116521-2936-1yk1132\node_modules\atom-package-manager\node_modules\first-mate\node_modules\oniguruma
> node-gyp rebuild

C:\Users\Felix\AppData\Local\Temp\apm-install-dir-116521-2936-1yk1132\node_modules\atom-package-manager\node_modules\first-mate\node_modules\oniguruma>if not defined npm_config_node_gyp (node "C:\Users\Felix\AppData\Local\atom\app-1.8.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild ) 

> git-utils@4.1.2 install C:\Users\Felix\AppData\Local\Temp\apm-install-dir-116521-2936-1yk1132\node_modules\atom-package-manager\node_modules\git-utils
> node-gyp rebuild

C:\Users\Felix\AppData\Local\Temp\apm-install-dir-116521-2936-1yk1132\node_modules\atom-package-manager\node_modules\git-utils>if not defined npm_config_node_gyp (node "C:\Users\Felix\AppData\Local\atom\app-1.8.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild ) 

npm WARN addRemoteGit Error: Command failed: 
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:658:15)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:98:17)
npm WARN addRemoteGit     at maybeClose (child_process.js:766:16)
npm WARN addRemoteGit     at Socket.<anonymous> (child_process.js:979:11)
npm WARN addRemoteGit     at Socket.emit (events.js:95:17)
npm WARN addRemoteGit     at Pipe.close (net.js:466:12)
npm WARN addRemoteGit  git+https://github.com/nathansobo/node-plist.git resetting remote C:\Users\Felix\.atom\.apm\_git-remotes\https-github-com-nathansobo-node-plist-git-32dc8646 because of error: { [Error: Command failed: ] killed: false, code: 1, signal: null }
npm WARN deprecated wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
gypnpm WARN deprecated minimatch@2.0.4: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
gypgypnpm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\Felix\\AppData\\Local\\atom\\app-1.8.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Felix\\AppData\\Local\\atom\\app-1.8.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Felix\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Felix\\.atom\\.apmrc" "install" "C:\\Users\\Felix\\AppData\\Local\\Temp\\d-116521-2936-els4ey\\package.tgz" "--target=0.36.8" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! keytar@3.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keytar@3.0.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the keytar package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls keytar
npm ERR! There is likely additional logging output above.

**Comment by hoseong613** [comment]
I have the same problem. It seems like pty.js build is failing.[https://github.com/chjj/pty.js/issues/131](url)
