### ISSUE TITLE
apm binding.mkdir

### ISSUE THREAD

**Issue by Nocturnal316** [atom/apm#614]
Hi I currently have an issue with apm when trying to install packages through the installer. I get the following error

```
 apm install activate-power-mode
Installing activate-power-mode to C:\Users\Polla\.atom\packages fs.js:794
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: ENOENT: no such file or directory, mkdir 'C:\Users\Polla\AppData\Local\Temp C:\Users\Polla\AppData\Local\atom\bin\d-11693-2396-syo8iq'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:794:18)
    at Object.mkdirSync (C:\Users\Polla\AppData\Local\atom\app-1.10.2\resources\app\apm\node_modules\temp\lib\temp.js:137:6)
    at Install.module.exports.Install.getPackageCachePath (C:\Users\Polla\AppData\Local\atom\app-1.10.2\resources\app\apm\lib\install.js:374:35)
    at C:\Users\Polla\AppData\Local\atom\app-1.10.2\resources\app\apm\lib\install.js:444:28
    at fn (C:\Users\Polla\AppData\Local\atom\app-1.10.2\resources\app\apm\node_modules\async\lib\async.js:582:34)
    at Immediate._onImmediate (C:\Users\Polla\AppData\Local\atom\app-1.10.2\resources\app\apm\node_modules\async\lib\async.js:498:34)
    at processImmediate [as _immediateCallback] (timers.js:383:17)


```

I've tried everything with not solutions.     i did echo %temp% and saw
C:\Users\Polla\AppData\Local\Temp C:\Users\Polla\AppData\Local\atom\bin

one thing that did work was downloading an older version of the atom installer  1.7.4. which allowed me to do apm installs but not install via atom editor itself.

**Comment by Nocturnal316** [comment]
Still need help with this... I still can't update packages via atom or apm

**Comment by plmsmile** [comment]
i met the same problem. Still need help with this... I still can't install packages via atom or apm.
