### ISSUE TITLE
Unable to build apm under Node v7.0.0

### ISSUE THREAD

**Issue by drewmnoel** [atom/apm#636]
**Description**:
When attempting to build Atom from source, the process fails out when installing apm. Probably related to #635 since I can build just fine if I revert to node v6.9.1.

**Steps to Reproduce:**
1. Have node v7.0.0 installed
2. Fresh clone of atom
3. Run `script/build`

**Stacktrace**:

```
child_process.js:145
    throw new TypeError('Incorrect value of args option');
    ^

TypeError: Incorrect value of args option
    at Object.exports.execFile (child_process.js:145:11)
    at Object.exports.exec (child_process.js:108:18)
    at Object.<anonymous> (/home/dnoel/src/atom/apm/node_modules/atom-package-manager/script/postinstall.js:10:16)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:382:7)
npm ERR! Linux 4.8.6-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "--global-style" "--loglevel=error" "install"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
    at checkExecSyncError (child_process.js:488:13)
    at Object.execFileSync (child_process.js:508:13)
    at module.exports (/home/dnoel/src/atom/script/lib/install-apm.js:10:16)
    at Object.<anonymous> (/home/dnoel/src/atom/script/bootstrap:27:1)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
```

**Comment by leo191** [comment]
I faced the same, so I also downgraded to v6.9.0 and I guess this problem is occurring only with arch variants.

**Comment by leo-mao** [comment]
same error here, wait for solution

**Comment by fusion809** [comment]
Same error here, if what the developers need is someone to confirm it I can.

**Comment by roasted-tea-leaves** [comment]
It was reproductive on my environment.
- macOS Sierra 10.12.1
- Node v7.2.0
- Npm v3.10.5
- xcode-select version 2345.1.

I might as well correct "Requirements".
(e.g. specify recommend version)
https://github.com/atom/atom/blob/master/docs/build-instructions/macos.md

**Comment by louisgv** [comment]
Confirmed with node v7.2.0 as well.

**Comment by drewmnoel** [comment]
There is already a fix merged in. Once the apm team tags it and atom pulls in the version bump builds will work again. We're not sure on an ETA for that, though.

**Comment by capouch** [comment]
Any updates on this?  I am having to maintain a whole Node v6 tree just to build atom, and this issue seems almost as old as I am.   Thanks.

**Comment by 50Wliu** [comment]
https://github.com/atom/atom/pull/13691

**Comment by kopax** [comment]
I have the same issue with node `v9.6.1`: 

    throw new TypeError('Incorrect value of args option');
