### ISSUE TITLE
apm install does not work

### ISSUE THREAD

**Issue by Nocturnal316** [atom/apm#643]
```
    Installing “activate-power-mode@1.1.0” failed.Hide output…
fs.js:794
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: ENOENT: no such file or directory, mkdir 'C:\Users\PollaDa\AppData\Local\Temp C:\Users\PollaDa\AppData\Local\atom\bin\d-1161010-9440-1ebbrwh'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:794:18)
    at Object.mkdirSync (C:\Users\PollaDa\AppData\Local\atom\app-1.12.0\resources\app\apm\node_modules\temp\lib\temp.js:137:6)
    at Request.<anonymous> (C:\Users\PollaDa\AppData\Local\atom\app-1.12.0\resources\app\apm\lib\install.js:332:41)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestResponse (C:\Users\PollaDa\AppData\Local\atom\app-1.12.0\resources\app\apm\node_modules\request\request.js:986:10)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:430:21)
```

**Comment by miguelroboso** [comment]
How did you solve this?
