### ISSUE TITLE
Atom package manager can not show any installed modules on Windows

### ISSUE THREAD

**Issue by TAXUEZJU** [atom/apm#700]
### Description
On latest Windows 10 Home Edition, there is some problem with atom package manager. After installation, nothing can show in Featured Packages in Settings. The error message is "Fetching featured packages failed", and  nothing shows after click "Show output". I have turned on Dev window, and find something like "uncaught error" in red. I am sure my network is OK, and atom's version is latest. I have tried to fully uninstall atom and delete all its directory and reinstall it. The problem still exists. I have tried clean install Windows and the problem still not be solved. My atom version and log file's content is below:
```
C:\Users\TAXUE>atom --version

Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```
and
```
task.coffee:84 spell-check:en-us Can't load en_US: Cannot find dictionary for en_US.
package-manager.coffee:149 Uncaught (in promise) Error: Fetching outdated packages and themes failed.
    at C:\Users\TAXUE\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:221:21
    at exit (C:\Users\TAXUE\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:99:16)
    at triggerExitCallback (C:\Users\TAXUE\AppData\Local\atom\app-1.15.0\resources\app.asar\src\buffered-process.js:322:11)
    at ChildProcess.<anonymous> (C:\Users\TAXUE\AppData\Local\atom\app-1.15.0\resources\app.asar\src\buffered-process.js:352:11)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
package-manager.coffee:85 Uncaught (in promise) Error: Fetching local packages failed.
    at C:\Users\TAXUE\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:142:19
    at exit (C:\Users\TAXUE\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:99:16)
    at triggerExitCallback (C:\Users\TAXUE\AppData\Local\atom\app-1.15.0\resources\app.asar\src\buffered-process.js:322:11)
    at ChildProcess.<anonymous> (C:\Users\TAXUE\AppData\Local\atom\app-1.15.0\resources\app.asar\src\buffered-process.js:352:11)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
apm
VM795:1 Uncaught ReferenceError: apm is not defined
    at <anonymous>:1:1(anonymous function) @ VM795:1

```
<img width="960" alt="1" src="https://cloud.githubusercontent.com/assets/10264706/23949017/76d79da2-09c0-11e7-9911-6aecb2aab71f.png">

**Comment by rsese** [comment]
Thanks for the report - I see a couple of similar reports [1] [2] in atom/settings-view so I think that might be the best place for this.  Can you open this issue in https://github.com/atom/settings-view?

[1]: https://github.com/atom/settings-view/issues/798
[2]: https://github.com/atom/settings-view/issues/533

**Comment by TAXUEZJU** [comment]
I have created issue in settings-view, link is here:[https://github.com/atom/settings-view/issues/924](url)
However, I can get nothing after execute "apm" or "apm --version" in "cmd.exe", is there any possbility that apm is not correctly recognized during installation. The problem still exists with the portable version. So I think there may be something wrong with apm not the settings-view.
@rsese
