### ISSUE TITLE
Packages not installing

### ISSUE THREAD

**Issue by natekfl** [atom/apm#778]
When installing packages, both through the gui and by doing `apm install [package]`, it returns the following error (Teletype used in this example):

I am using atom on Windows 10 and have the latest version of Node installed.

```Installing teletype to C:\Users\Nathan Kutzan\.atom\packages failed
C:\Users\NATHAN~1\AppData\Local\Temp\apm-install-dir-118221-4396-195c4ur.q45f1lwhfr
-- (empty)


npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\NATHAN~1\AppData\Local\Temp\apm-install-dir-118221-4396-195c4ur.q45f1lwhfr\package.json'
npm WARN apm-install-dir-118221-4396-195c4ur.q45f1lwhfr No description
npm WARN apm-install-dir-118221-4396-195c4ur.q45f1lwhfr No repository field.
npm WARN apm-install-dir-118221-4396-195c4ur.q45f1lwhfr No README data
npm WARN apm-install-dir-118221-4396-195c4ur.q45f1lwhfr No license field.
npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Users\\Nathan Kutzan\\AppData\\Local\\atom\\app-1.25.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Nathan Kutzan\\AppData\\Local\\atom\\app-1.25.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Nathan Kutzan\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Nathan Kutzan\\.atom\\.apmrc" "install" "C:\\Users\\NATHAN~1\\AppData\\Local\\Temp\\d-118221-4396-t354s0.2w9971fw29\\package.tgz" "--runtime=electron" "--target=1.7.11" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! path C:\Users\NATHAN~1\AppData\Local\Temp\apm-install-dir-118221-4396-195c4ur.q45f1lwhfr\node_modules\.staging\event-kit-8dc980ad
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\NATHAN~1\AppData\Local\Temp\apm-install-dir-118221-4396-195c4ur.q45f1lwhfr\node_modules\.staging\event-kit-8dc980ad' -> 'C:\Users\NATHAN~1\AppData\Local\Temp\apm-install-dir-118221-4396-195c4ur.q45f1lwhfr\node_modules\teletype\node_modules\event-kit'
npm ERR!     at destStatted (C:\Users\Nathan Kutzan\AppData\Local\atom\app-1.25.0\resources\app\apm\node_modules\npm\lib\install\action\finalize.js:25:7)
npm ERR!     at C:\Users\Nathan Kutzan\AppData\Local\atom\app-1.25.0\resources\app\apm\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\NATHAN~1\AppData\Local\Temp\apm-install-dir-118221-4396-195c4ur.q45f1lwhfr\node_modules\.staging\event-kit-8dc980ad' -> 'C:\Users\NATHAN~1\AppData\Local\Temp\apm-install-dir-118221-4396-195c4ur.q45f1lwhfr\node_modules\teletype\node_modules\event-kit'
npm ERR!     at Error (native)
npm ERR!  { Error: EPERM: operation not permitted, rename 'C:\Users\NATHAN~1\AppData\Local\Temp\apm-install-dir-118221-4396-195c4ur.q45f1lwhfr\node_modules\.staging\event-kit-8dc980ad' -> 'C:\Users\NATHAN~1\AppData\Local\Temp\apm-install-dir-118221-4396-195c4ur.q45f1lwhfr\node_modules\teletype\node_modules\event-kit'
npm ERR!     at destStatted (C:\Users\Nathan Kutzan\AppData\Local\atom\app-1.25.0\resources\app\apm\node_modules\npm\lib\install\action\finalize.js:25:7)
npm ERR!     at C:\Users\Nathan Kutzan\AppData\Local\atom\app-1.25.0\resources\app\apm\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\NATHAN~1\AppData\Local\Temp\apm-install-dir-118221-4396-195c4ur.q45f1lwhfr\node_modules\.staging\event-kit-8dc980ad' -> 'C:\Users\NATHAN~1\AppData\Local\Temp\apm-install-dir-118221-4396-195c4ur.q45f1lwhfr\node_modules\teletype\node_modules\event-kit'
npm ERR!     at Error (native) parent: 'teletype' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\NATHAN~1\AppData\Local\Temp\apm-install-dir-118221-4396-195c4ur.q45f1lwhfr\npm-debug.log
npm ERR! code 1```

**Comment by rsese** [comment]
Thanks for moving this over @natekfl :+1:

Did you also have 1.24 (or older) installed and had no trouble there and after updating to 1.25 you started seeing this problem?

Also this part of the error looks interesting?

> npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\NATHAN~1\AppData\Local\Temp\apm-install-dir-118221-4396-195c4ur.q45f1lwhfr\node_modules\.staging\event-kit-8dc980ad' -> 'C:\Users\NATHAN~1\AppData\Local\Temp\apm-install-dir-118221-4396-195c4ur.q45f1lwhfr\node_modules\teletype\node_modules\event-kit'

Looks like a permissions issue renaming something in your temp directory which is odd?  I found this while searching around (it seems to be reported in a number of projects) where a similar error popped up:

https://github.com/react-community/create-react-native-app/issues/191

Some folks mention that disabling antivirus helped - can you give that a try?

**Comment by natekfl** [comment]
Seems like turning off my antivirus (Malwarebytes) seemed to work. Thanks for the help 👍

**Comment by rsese** [comment]
Glad that helped, we'll go ahead and close for now :v:
