### ISSUE TITLE
Failed package installation

### ISSUE THREAD

**Issue by krrevilla** [atom/apm#807]
### Description

[Description of the issue]

### Steps to Reproduce

1. Install Atom (1.29.0)
2. Install Nuclide package

**Expected behavior:** [What you expect to happen]
1. Successful installation of Nuclide

**Actual behavior:** [What actually happens]
1. Installing “nuclide@0.332.0” failed.

```
/usr/share/atom/resources/app/apm/lib/install.js:313
          if (body.releases.latest) {

TypeError: Cannot read property 'latest' of undefined
    at /usr/share/atom/resources/app/apm/lib/install.js:313:28
```

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

**Atom**
Atom    : 1.29.0
Electron: 2.0.5
Chrome  : 61.0.3163.100
Node    : 8.9.3

**APM**
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.29.0
python 2.7.15rc1
git 2.17.1

**Comment by smashwilson** [comment]
It looks like the request to https://atom.io/api/packages/nuclide is returning successfully, but doesn't have the expected JSON structure. Hitting that endpoint manually, the payload _looks_ well-formed.

Can you try running `apm install nuclide --verbose` to trace network requests?

Also, are you behind a proxy?

**Comment by krrevilla** [comment]
@smashwilson 
```
REQUEST end event https://atom.io/api/packages/nuclide
REQUEST has body https://atom.io/api/packages/nuclide 130320
REQUEST invalid JSON received https://atom.io/api/packages/nuclide
REQUEST emitting complete https://atom.io/api/packages/nuclide
/usr/share/atom/resources/app/apm/lib/install.js:313
          if (body.releases.latest) {
                           ^

TypeError: Cannot read property 'latest' of undefined
    at /usr/share/atom/resources/app/apm/lib/install.js:313:28
    at Request._callback (/usr/share/atom/resources/app/apm/lib/request.js:56:22)
    at Request.self.callback (/usr/share/atom/resources/app/apm/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/request/request.js:1085:12)
    at IncomingMessage.g (events.js:291:16)
```
What do you mean if im behind a proxy ?

**Comment by rsese** [comment]
Are you connecting from your home network, or from somewhere like a university or corporate network @krrevilla?  If you connect from a different network temporarily to test, do you have the same issue?

**Comment by krrevilla** [comment]
I've encountered another error when installing some themes and packages. 

e.g. `apm install material` it gives error

npm ERR! tar.unpack unzip error /tmp/d-118716-5167-1bdmoge.4v9gzj8aor/package.tgz
npm ERR! addLocal Could not install /tmp/d-118716-5167-1bdmoge.4v9gzj8aor/package.tgz
npm ERR! Linux 4.15.0-32-generic
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/karlrevilla/.atom/.apm/.apmrc" "--userconfig" "/home/karlrevilla/.atom/.apmrc" "install" "/tmp/d-118716-5167-1bdmoge.4v9gzj8aor/package.tgz" "--runtime=electron" "--target=2.0.5" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code Z_BUF_ERROR
npm ERR! errno -5

npm ERR! unexpected end of file
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-118716-5167-1ixb7hc.6j8nuvunmi/npm-debug.log

**Comment by rsese** [comment]
> I've encountered another error when installing some themes and packages.

Just to clarify, did you get past the original error you were seeing when installing Nuclide and now some (but not all) packages and themes are giving you this new error when you try to install them?
