### ISSUE TITLE
Can't install packet behind proxy

### ISSUE THREAD

**Issue by Maladra** [atom/apm#848]
I can't install packet error 502 behind a corporate Proxy Proxy is set and strict-ssl is to false

Here the command ouput
 ```
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@8.9.3 | linux | x64
gyp http GET https://atom.io/download/electron/v2.0.18/iojs-v2.0.18.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! install error 
gyp ERR! stack Error: tunneling socket could not be established, statusCode=502
gyp ERR! stack     at ClientRequest.onConnect (/usr/share/atom/resources/app/apm/node_modules/tunnel-agent/index.js:166:19)
gyp ERR! stack     at Object.onceWrapper (events.js:319:30)
gyp ERR! stack     at emitThree (events.js:136:13)
gyp ERR! stack     at ClientRequest.emit (events.js:217:7)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:472:11)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at Socket.emit (events.js:211:7)
gyp ERR! stack     at addChunk (_stream_readable.js:263:12)
gyp ERR! stack     at readableAddChunk (_stream_readable.js:250:11)
gyp ERR! stack     at Socket.Readable.push (_stream_readable.js:208:10)
gyp ERR! System Linux 4.15.0-50-generic
gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/node-gyp/bin/node-gyp.js" "install" "--runtime=electron" "--target=2.0.18" "--dist-url=https://atom.io/download/electron" "--arch=x64" "--ensure" "--proxy=http://<proxy>:<port>/"
gyp ERR! cwd /home/myhome/.atom
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

```

**Comment by rsese** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

---

I also noticed that you had a similar problem outside of Atom in https://github.com/atom/apm/issues/827?  So it seems like a general issue related to your proxy/proxy settings rather than something specific to Atom?
