### ISSUE TITLE
Native module install errors with latest nightly release

### ISSUE THREAD

**Issue by Aerijo** [atom/apm#860]
### Prerequisites

na

### Description

When building a native module, it will throw the following error
```
gyp: Call to 'node -e "require('nan')"' returned exit status 134 while in binding.gyp. while trying to load binding.gyp
```
This call appears in the `binding.gyp` of most native modules, but not the test module bundled in apm, so the build tools check does not pick it up.

### Steps to Reproduce

1. Run `apm-nightly install termination`
2. Observe error similar to following
<details>
  <summary>Error message</summary>

```
22:35 $ apm-nightly install termination
Installing termination to /home/benjamin/.atom/packages ✗

> node-pty-prebuilt@0.7.6 install /tmp/apm-install-dir-119624-10760-7pdou5.9pgq/node_modules/termination/node_modules/node-pty-prebuilt
> prebuild-install || node scripts/install.js


Aborted (core dumped)
Aborted (core dumped)
gyp: Call to 'node -e "require('nan')"' returned exit status 134 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/atom-nightly/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Linux 5.0.0-21-generic
gyp ERR! command "/usr/share/atom-nightly/resources/app/apm/bin/node" "/usr/share/atom-nightly/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--build_v8_with_gn=false"
gyp ERR! cwd /tmp/apm-install-dir-119624-10760-7pdou5.9pgq/node_modules/termination/node_modules/node-pty-prebuilt
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
Aborted (core dumped)
Aborted (core dumped)
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-119624-10760-7pdou5.9pgq/package.json'
npm WARN apm-install-dir-119624-10760-7pdou5.9pgq No description
npm WARN apm-install-dir-119624-10760-7pdou5.9pgq No repository field.
npm WARN apm-install-dir-119624-10760-7pdou5.9pgq No README data
npm WARN apm-install-dir-119624-10760-7pdou5.9pgq No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! node-pty-prebuilt@0.7.6 install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the node-pty-prebuilt@0.7.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/benjamin/.atom/.apm/_logs/2019-07-24T12_36_29_137Z-debug.log
```

</details>

**Expected behavior:**

Build without issue

**Actual behavior:**

Error

**Reproduces how often:**

100%

### Versions

```
22:40 $ apm-nightly -v
apm  2.4.2
npm  6.2.0
node 10.2.1 x64
atom 1.41.0-nightly1
python 2.7.16
git 2.20.1
```

### Additional Information

This issue does not occur with apx. AFAIK, the most significant difference is for apx I pass the build config via [environment](https://github.com/Aerijo/apx/blob/3a9fe2f5036b6a93019bd083f31fe0dca5611b53/src/install.ts#L34) [variables](https://github.com/Aerijo/apx/blob/3a9fe2f5036b6a93019bd083f31fe0dca5611b53/src/context.ts#L219), and no flags.

**Comment by rsese** [comment]
Thanks @Aerijo - looks like you're on Linux so I tried to reproduce on an Ubuntu 19.04 vm with 1.41.0-nightly1 but it completed successfully:

```
rsese@ubuntu:~$ atom-nightly -v
Atom    : 1.41.0-nightly1
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0
rsese@ubuntu:~$ apm-nightly -v
apm  2.4.2
npm  6.2.0
node 10.2.1 x64
atom 1.41.0-nightly1
python 2.7.16
git 2.20.1
rsese@ubuntu:~$ apm-nightly install termination
Installing termination to /home/rsese/.atom/packages ✓
```

Assuming if you install with stable or beta you don't get the same error?

**Comment by Aerijo** [comment]
It is Linux 19.04, and only nightly. Interesting, I’ll look into it some more.

**Comment by Aerijo** [comment]
@rsese I tried on a fresh Ubuntu 19.04 vm, and while I didn't get any errors, I got an incompatible NODE_MODULE_VERSION. It's a different error, but do you know if the terminal actually worked in your steps?

**Comment by rsese** [comment]
> , I got an incompatible NODE_MODULE_VERSION. It's a different error, but do you know if the terminal actually worked in your steps?

Ahh yeah, after starting nightly I see the same incompatible package error :+1:   I'll go ahead and reopen and reference from your PR.

**Comment by zipy124** [comment]
As show by the reference this is not fixed and this issue should be re-opened. I have reproduced on both the stable 1.44.0 version and the nightly version 1.46.0-nightly3. The same error message is received when trying to install any number of packages.

example failed install log:

```> ptyw.js@0.4.1 install /tmp/apm-install-dir-120128-16988-1w6a7ld.1i42/node_modules/term3/node_modules/ptyw.js
> node-gyp rebuild


npm WARN deprecated react-tools@0.11.2: react-tools is deprecated. For more information, visit https://fb.me/react-tools-deprecated
npm WARN deprecated graceful-fs@2.0.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
Aborted (core dumped)
gyp: Call to 'node -e "require('nan')"' returned exit status 134 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/atom-nightly/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Linux 5.0.0-38-generic
gyp ERR! command "/usr/share/atom-nightly/resources/app/apm/bin/node" "/usr/share/atom-nightly/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-120128-16988-1w6a7ld.1i42/node_modules/term3/node_modules/ptyw.js
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
Aborted (core dumped)
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-120128-16988-1w6a7ld.1i42/package.json'
npm WARN apm-install-dir-120128-16988-1w6a7ld.1i42 No description
npm WARN apm-install-dir-120128-16988-1w6a7ld.1i42 No repository field.
npm WARN apm-install-dir-120128-16988-1w6a7ld.1i42 No README data
npm WARN apm-install-dir-120128-16988-1w6a7ld.1i42 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! ptyw.js@0.4.1 install: `node-gyp rebuild`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the ptyw.js@0.4.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/uclapi/.atom/.apm/_logs/2020-02-28T16_34_52_625Z-debug.log```
