### ISSUE TITLE
Uncaught AssertionError [ERR_ASSERTION]: 16838 == 0

### ISSUE THREAD

**Issue by raoniz** [atom/apm#863]
### Prerequisites

* [x] Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
* [x] Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
* [x] Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
* [x] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
* [x] Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I work in an environment involving corporate proxy thus, configured proxy settings referring [this](https://github.com/atom/apm#using-a-proxy). Later which, I got self signed certificate error and I tried resolving it by referring [this](https://discuss.atom.io/t/im-getting-an-error-about-a-self-signed-certificate-what-do-i-do/39040). After disabling ssl check, I am still getting the certificate error as well as the mentioned 'Assertion Error'.

> Certificate Error: self signed certificate in certificate chain

I am unable to download packages through atom or apm, the non-core packages are downloaded manually by me.

### Steps to reproduce

1. Execute following commands:
```bash
apm set config http_proxy=http://proxy.servername:port
apm set config https_proxy=http://proxy.servername:port
apm set config strict-ssl=false
```
2. Open Atom Settings `(Ctrl + ,)`.
3. Search for any package name.

**Atom**: 1.39.1 x64
**Electron**: 3.1.10
**OS**: Microsoft Windows 8.1 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught AssertionError [ERR_ASSERTION]: 16838 == 0

```
At assert.js:79

AssertionError [ERR_ASSERTION]: 16838 == 0
    at ClientRequest.onConnect (/app.asar/node_modules/tunnel-agent/index.js:160:14)
    at Object.onceWrapper (events.js:273:13)
    at ClientRequest.emit (events.js:182:13)
    at Socket.socketOnData (_http_client.js:465:11)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:636:20)
```

### Commands

```
     -0:14.6.0 window:toggle-dev-tools (atom-pane.pane.active)
```

### Non-Core Packages

```
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
Hydrogen 2.10.3 
teletype 0.13.4 
```

**Comment by rsese** [comment]
> I am unable to download packages through atom or apm

...

> * Open Atom Settings `(Ctrl + ,)`.

It sounds like this is the case, but just to confirm you also have the same issue when using apm from the command line?

**Comment by raoniz** [comment]
Yes, same Assertion Error occurs while using apm from the command line.

**Comment by raoniz** [comment]
@kevinsawicki @zcbenz @smashwilson @50Wliu 
Kindly help.

**Comment by rsese** [comment]
> http_proxy=http://servername:port
> https_proxy=http://servername:port

I'm guessing it might not make a difference, but [what's documented](https://github.com/atom/apm/#using-a-proxy) and what I've seen people try is with an hyphen rather than an underscore (`https-proxy` vs `httpx_proxy`).  Just in case though, can you give that a try?

About problems with proxies in general, this has been discussed in https://github.com/atom/apm/issues/772#issuecomment-445298119 and https://github.com/atom/apm/issues/772#issuecomment-445554199; we're currently unable to test all the different proxy configurations so if someone runs into an issue, we're not in a place where we can prioritize investigating why there's a problem with someone's setup unfortunately.

**Comment by er-raoniz** [comment]
Thanks for the response.
> I've seen people try is with an hyphen rather than an underscore (https-proxy vs httpx_proxy).

I tried replacing it with a _hyphen_ but, that didn't help.
> About problems with proxies in general, this has been discussed in #772 (comment) and #772 (comment); we're currently unable to test all the different proxy configurations so if someone runs into an issue, we're not in a place where we can prioritize investigating why there's a problem with someone's setup unfortunately.

Yeah, I noticed the issue a few days ago, there are many people reporting _proxy issue_ (which is implemented in _most of the corporate environments_). I understand your concern about prioritizing other issues and I'll wait to get it resolved.

> **Suggestion: I do use VS Code and it smoothly allows installation of packages. Can the proxy issues of Atom be configured on the lines of VS Code to resolve the issue?**
