### ISSUE TITLE
fatal: Authentication failed

### ISSUE THREAD

**Issue by drom** [atom/apm#907]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

I am trying to publish a new version of my package and getting this error:

```
drom@linux-sydi:~/work/github/drom/atom-hide> apm publish 0.7.22
Preparing and tagging a new version ✓
Pushing v0.7.22 tag ✗
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/drom/atom-hide/'
```

### Steps to Reproduce

1. `apm login`
2. `apm publish 0.7.22`

**Expected behavior:**

Expected `publish` to work.

**Actual behavior:**

`publish` doesn't work

**Reproduces how often:**

For the last 14 times I have tried today.

### Versions

```
drom@linux-sydi:~/work/github/drom/atom-hide> apm --version
apm  2.5.2
npm  6.14.8
node 12.4.0 x64
atom 1.52.0
python 2.7.18
git 2.28.0
```

```
drom@linux-sydi:~/work/github/drom/atom-hide> uname -a
Linux linux-sydi 5.8.14-1-default #1 SMP Wed Oct 7 06:23:04 UTC 2020 (cea47bb) x86_64 x86_64 x86_64 GNU/Linux
```

### Additional Information

I have tried to login with atom.io and github.com tokens.

**Comment by vt5491** [comment]
1. Pretty much the same for me, when I tried from windows:
```
vturner2@LAPTOP-F0QM306P MINGW64 ~/.atom/dev/packages/multi-theme-applicator (master)

$ apm publish patch
Preparing and tagging a new version done
Pushing v2.3.2 tag failed
fatal: HttpRequestException encountered.
   An error occurred while sending the request.

Unhandled Exception: System.ObjectDisposedException: Cannot access a closed file.
   at System.IO.__Error.FileNotOpen()
   at System.IO.FileStream.Flush(Boolean flushToDisk)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at Microsoft.Alm.Git.Trace.Microsoft.Alm.Git.ITrace.Flush()
   at Microsoft.Alm.Cli.Program.Die(String message)
   at Microsoft.Alm.Cli.Program.Die(Exception exception)
   at Microsoft.Alm.Cli.Program.Main(String[] args)
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/vt5491/multi-theme-applicator/'

$ apm --version
apm  2.6.2
npm  6.14.13
node 12.14.1 x64
atom 1.60.0
python 2.7
git 2.12.1.windows.1
visual studio 2017
```
2. Fortunately, I was able to get it to work from a linux VM:

```
vturner@vturner-virtual-machine ~/vtstuff/github/multi-theme-applicator $ apm publish patch
Preparing and tagging a new version ✓
Pushing v2.2.5 tag Username for 'https://github.com': vt5491
Password for 'https://vt5491@github.com': 

vturner@vturner-virtual-machine ~/vtstuff/github/multi-theme-applicator/lib $ apm --version
apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.40.1
python 2.7.12
git 2.7.4

```
for password I specified a 30-day "personal access token" that I generated on github, which looked something like:

ghp_FT0ogVuU7YgySVwekSWqCyOvD.........

which was I token I granted all privileges to.  Don't know if granting all repo privileges is strictly necessary though.  Don't use the token that is given to you when you use 'apm login'. 

3. use "git reset HEAD~n" if you need to delete any local publish commits that failed.
